#!/usr/bin/env node
// bubble-load — turns bubble-export's schema.json into Postgres DDL, per the
// bubble-db-migration skill's type-mapping table (§3) and load-order rules
// (§2.3/§6: defer FK constraints until after load). DDL generation is
// implemented; the actual load stage is scaffolded. Node.js 18+, zero deps.
//
// Usage: node bubble-load.mjs <ddl|load> [flags]

import { parseArgs } from 'node:util';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const HELP = `bubble-load — load bubble-export output into Postgres

Commands:
  ddl    schema.json -> schema.sql (implemented)
  load   NDJSON -> Postgres COPY/upsert (scaffold)

Flags:
  ddl: --in <dir>    bubble-export output dir (default ./bubble-export-out)
       --out <file>  SQL path (default <in>/schema.sql)
`;

const ident = (name) => `"${name.replace(/"/g, '""')}"`;

// Generate CREATE TABLE statements from a bubble-export schema plan.
// Encodes the skill's §3 mapping: Bubble _id as TEXT PRIMARY KEY, list-of-Things
// as ordered junction tables, option sets as TEXT + lookup tables, an _extra
// JSONB column for schema drift, an index on modified_date (drives incremental
// sync), and FK constraints emitted LAST in a separate section.
export function generateDdl(plan) {
  const tables = [];
  const junctions = [];
  const lookups = new Set();
  const fks = [];
  const skip = new Set(['_id']);

  for (const [typeName, type] of Object.entries(plan.types)) {
    const table = toTableName(typeName);
    const cols = [`  ${ident('_id')} TEXT PRIMARY KEY`];
    for (const [field, spec] of Object.entries(type.fields)) {
      if (skip.has(field)) continue;
      const col = spec.column;
      switch (spec.sql) {
        case 'JUNCTION_TABLE': {
          // Bubble lists are ordered and the order is often meaningful (§9.7).
          const jt = `${table}_${col}`;
          junctions.push(
            `CREATE TABLE ${ident(jt)} (\n` +
            `  ${ident('parent_id')} TEXT NOT NULL,\n` +
            `  ${ident('child_id')} TEXT NOT NULL,\n` +
            `  ${ident('position')} INTEGER NOT NULL,\n` +
            `  PRIMARY KEY (${ident('parent_id')}, ${ident('position')})\n` +
            `);`,
          );
          fks.push(`ALTER TABLE ${ident(jt)} ADD FOREIGN KEY (${ident('parent_id')}) REFERENCES ${ident(table)} (${ident('_id')});`);
          continue;
        }
        case 'ARRAY':
          cols.push(`  ${ident(col)} TEXT[]`);
          continue;
        default:
          cols.push(`  ${ident(col)} ${spec.sql}`);
      }
      if (spec.inferred === 'option_set') {
        // Option sets are returned as display values only (§1); accumulate the
        // distinct values into a lookup table during load.
        lookups.add(`CREATE TABLE IF NOT EXISTS ${ident(`option_set_${col}`)} (${ident('value')} TEXT PRIMARY KEY);`);
      }
      if (spec.inferred === 'reference') {
        // Referenced type is unknowable from a single field; validate against
        // exported IDs post-load, then point the FK at the right table.
        fks.push(`-- TODO: set target table for ${table}.${col}, then:\n-- ALTER TABLE ${ident(table)} ADD FOREIGN KEY (${ident(col)}) REFERENCES <target> ("_id");`);
      }
    }
    cols.push(`  ${ident('_extra')} JSONB`); // schema drift landing zone (§5.6)
    tables.push(`CREATE TABLE ${ident(table)} (\n${cols.join(',\n')}\n);`);
    if (Object.values(type.fields).some((f) => f.column === 'modified_date')) {
      tables.push(`CREATE INDEX ON ${ident(table)} (${ident('modified_date')});`);
    }
  }

  return [
    '-- Generated by bubble-load from a bubble-export schema plan.',
    '-- Review before applying: type inference is a starting point, not a decision.',
    '',
    '-- ── Base tables ──',
    ...tables,
    '',
    '-- ── Junction tables (ordered lists of Things) ──',
    ...junctions,
    '',
    '-- ── Option-set lookup tables ──',
    ...lookups,
    '',
    '-- ── Foreign keys: APPLY AFTER LOAD ──',
    '-- Load order: base tables -> junction tables -> validate dangling references -> FKs.',
    '-- Applying FKs up front is the classic way these migrations die at 80% (skill §2.3).',
    ...fks,
    '',
  ].join('\n');
}

export function toTableName(typeName) {
  const s = typeName.normalize('NFKD').replace(/[^\w\s-]/g, '').trim()
    .replace(/[-\s]+/g, '_').replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
  return /^\d/.test(s) ? `t_${s}` : s || 'unnamed_type';
}

function cmdDdl(flags) {
  const inDir = flags.in ?? './bubble-export-out';
  const planFile = join(inDir, 'schema.json');
  if (!existsSync(planFile)) { console.error(`error: ${planFile} not found — run "bubble-export discover" first`); process.exit(1); }
  const plan = JSON.parse(readFileSync(planFile, 'utf8'));
  const sql = generateDdl(plan);
  const outFile = flags.out ?? join(inDir, 'schema.sql');
  writeFileSync(outFile, sql);
  console.log(`DDL for ${Object.keys(plan.types).length} type(s) -> ${outFile}`);
  console.log('Review the SQL (and the TODO FK targets) before applying.');
}

// TODO(scaffold): implement the load stage per skill §6.
function cmdLoad() {
  console.log('load: NOT IMPLEMENTED (scaffold). A full implementation will:');
  for (const l of [
    'bulk-load base tables from NDJSON via COPY (or psql \\copy), FKs deferred',
    'explode list-of-Things fields into junction rows preserving position',
    'accumulate distinct option-set values into the lookup tables',
    'upsert keyed on _id for incremental sync deltas (deltas/<ts>/ dirs)',
    'validate dangling references against the exported ID sets, resolve per policy (null out / FK disabled / fail)',
    'apply FK constraints LAST',
  ]) console.log(`  - ${l}`);
  console.log('Note: a real load needs a Postgres driver (outside this kit\'s zero-dependency rule) or shells out to psql. See the bubble-db-migration skill §6.');
  process.exit(2);
}

function main() {
  const { values, positionals } = parseArgs({
    args: process.argv.slice(2),
    allowPositionals: true,
    options: { in: { type: 'string' }, out: { type: 'string' }, help: { type: 'boolean' } },
  });
  const command = positionals[0];
  if (values.help || !command) { console.log(HELP); process.exit(command ? 0 : 1); }
  const commands = { ddl: cmdDdl, load: cmdLoad };
  const fn = commands[command];
  if (!fn) { console.error(`unknown command: ${command}\n${HELP}`); process.exit(1); }
  fn(values);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
